# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          install: true
          command: npm run cypress-run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: report
          path: ./mochawesome-report
        
